services:
  - type: web
    name: miaoshou-app
    env: node
    region: singapore
    branch: customer
    buildCommand: npm install && npm run build
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: OPENAI_BASE_URL
        value: https://www.zzshu.cc/v1
      - key: OPENAI_MODEL
        value: gpt-image-2
      - key: NODE_TLS_REJECT_UNAUTHORIZED
        value: "0"
      - key: NODE_ENV
        value: production
